### ISSUE TITLE
Reproduce the paper result

### ISSUE THREAD

**Issue by kexul** [michellab/ACK1_Data#1]
Dear authors: 
I'm trying to reproduce the result reported in your paper. Here I selected pair **6**~**7** in batch 1 to conduct my experiments: 
Paper result (without bridging water): 
![企业微信截图_16552853822586](https://user-images.githubusercontent.com/5920217/174065528-9df6a94e-b6df-4e5c-9ae7-75f1244e572c.png)
Paper result (With bridging water):
![企业微信截图_16552854748600](https://user-images.githubusercontent.com/5920217/174065569-2c5d022c-ea1c-4e7c-9a7b-ddba1a2f9c6d.png)

However, in my experiments with 3 runs, the result seems to agree to some extent no matter the water molecule is present or not:
With bridging water:
|      | run1      | run2      | run3      | average   |
| ---- | --------- | --------- | --------- | --------- |
| 6->7 | \-1.96839 | \-0.99953 | \-1.49725 | \-1.48839 |
| 7->6 | 1.093424  | 1.261834  | 0.90991   | 1.088389  |

Without bridging water: 
|      | run1      | run2      | run3     | average   |
| ---- | --------- | --------- | -------- | --------- |
| 6->7 | \-2.05594 | \-1.14081 | \-1.2084 | \-1.46838 |
| 7->6 | 1.941199  | 1.224871  | 0.948141 | 1.371404  |

My system was prepared by BioSimSpace and equilibrated by Groamcs, here are the script and input files I used: 
[temp.zip](https://github.com/michellab/ACK1_Data/files/8919064/temp.zip)

Should I compare more pairs of ligands to validate the result? Or check my pipeline to ensure there is no systematic error in my system preparation procedure?  Any suggestion is appreciated!

**Comment by jmichel80** [comment]
Hi @kexul the work reported in this paper was done with a different FEP pipeline that predated BioSimSpace so it is possible that the results are not reproducible with a different protocol. Check if after equilibration a bulk water molecule has diffused in to occupy  the space occupied by the bridging water in the other setup protocol. This would explain why the results are similar between your two setups.

**Comment by kexul** [comment]
Thanks @jmichel80 , I do see a bulk water molecule inside the pocket after equilibration.  
![企业微信截图_16554475171203](https://user-images.githubusercontent.com/5920217/174239247-a32fdfe3-5dc1-4876-9c9f-0b0a2ca79e8e.png)
